Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace admin_panel.Models
{
    public class LoginViewModel
    {
        public string userName { get; set; } = null!;

        [DataType(DataType.Password)] 
        public string password { get; set; } = null!;

    }
    
}

Controllers/AdminController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using admin_panel.Models;
using admin_panel.Data;
using admin_panel.Entity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;


namespace admin_panel.Controllers;

public class AdminController : Controller
{
    

    private readonly MyContext _context;
    public AdminController(MyContext context)
    {
        _context = context;
        
     
    }

    
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    
    public async Task<IActionResult> Index(LoginViewModel model)
    {
        if(ModelState.IsValid)
        {
            if(!string.IsNullOrEmpty(model.userName) && !string.IsNullOrEmpty(model.password))
            {
                var user =await _context.users.AnyAsync(x => x.userName == model.userName && x.password == model.password);
                if(user)
                {              
                    HttpContext.Session.SetString("IsUserLoggedIn","true");
                    
                    return View("AdminIndex");
                }
                
            }
        }

        return View();
    }

   
    public async Task<IActionResult> AdminIndex()
    {
        string? Giris = HttpContext.Session.GetString("IsUserLoggedIn");  
        if(Giris != null)
        {
            
            if(Giris == "true")
            {               
                var viewModel = new CountViewModel
                    {
                        YemekCount =await _context.urunler.Where(x => x.kategoriId == 1).CountAsync(),
                        AlkolCount = await _context.urunler.Where(x => x.kategoriId == 2).CountAsync(),
                        IcecekCount = await _context.urunler.Where(x => x.kategoriId == 3).CountAsync(),
                        ExtraCount = await _context.urunler.Where(x => x.kategoriId == 4).CountAsync(),
                        KampanyaCount =await  _context.urunler.Where(x => x.kategoriId == 5).CountAsync() 
                    };
                 return View(viewModel);
            }else{
                return RedirectToAction("Index");
            }
        }else{
            return RedirectToAction("Index");
        }        
    }
   

    public async Task<IActionResult> Menu(string category)
    {
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
            ViewBag.category = category;
        
            if(category == "hepsi")
            {
                var allProduct = await _context.urunler.ToListAsync();
                return View(allProduct);
            }else{
                var filteredProduct = await _context.urunler
                                            .Include(x => x.Tablo)
                                            .Where(x => x.Tablo.tabloName == category)
                                            .ToListAsync();
                return View(filteredProduct);
            }
        }else{
            return View("Index");
        }
      
    }  

    [HttpGet]
    public IActionResult GetTablolarByKategoriId(int kategoriId)
    {
         var tablolar = _context.tablolar.Where(t => t.kategoriId == kategoriId).ToList();
    
        // JSON olarak tabloları dön
        return Json(tablolar);
    }

    

}

Controllers/CreateController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using admin_panel.Models;
using admin_panel.Data;
using admin_panel.Entity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin_panel.Controllers;

public class CreateController : Controller
{
    private readonly MyContext _context;

    public CreateController(MyContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Kampanya()
    {   
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {

            
            return View();
        }else{
            return RedirectToAction("Index","Admin");
        }  
    }

    [HttpPost]
public async Task<IActionResult> Kampanya(UrunViewModel urunViewModel)
{
    try
    {
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
            if(ModelState.IsValid)
            {
                    // ViewModel'den asıl veritabanı modeline dönüştürme
                var urun = new Urun
                {
                    Name = urunViewModel.Name,
                    Description = urunViewModel.Description,
                    Amount = urunViewModel.Amount,
                    tabloId = urunViewModel.tabloId,
                    kategoriId = urunViewModel.kategoriId
                };
                _context.urunler.Add(urun);
                await _context.SaveChangesAsync();

                return RedirectToAction("AdminIndex","Admin");
            }
            else
            {
                
                return View();
            }
            
        }
        else
        {
            return RedirectToAction("Index","Admin");
        }
    }
    catch(Exception ex)
    {
        // Hata durumunda yapılacak işlemleri burada ele alabilirsiniz
        // Örneğin, hata mesajını loglamak, kullanıcıya hata mesajını göstermek gibi
        // Örnek olarak hata mesajını konsola yazdıralım:
        Console.WriteLine("Hata Oluştu: " + ex.Message);

        // İstisna durumu ele alındıktan sonra uygun bir şekilde kullanıcıya yönlendirme yapabilirsiniz.
        // Örneğin, bir hata sayfasına yönlendirme yapabilirsiniz.
        return RedirectToAction("Hata", "Home");
    }
}

    [HttpGet]
    public IActionResult Index()
    {   
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {

            ViewBag.Kategoriler = new SelectList(_context.kategoriler.ToList(),"kategoriId","kategoriName"); 
            ViewBag.Tablolar = new SelectList(_context.tablolar.ToList(),"tabloId","tabloName");
            return View();
        }else{
            return RedirectToAction("Index","Admin");
        }
        
    }

    [HttpPost]
public async Task<IActionResult> Index(UrunViewModel urunViewModel)
{
    try
    {
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
            if(ModelState.IsValid)
            {
                    // ViewModel'den asıl veritabanı modeline dönüştürme
                var urun = new Urun
                {
                    Name = urunViewModel.Name,
                    Description = urunViewModel.Description,
                    Amount = urunViewModel.Amount,
                    tabloId = urunViewModel.tabloId,
                    kategoriId = urunViewModel.kategoriId
                };
                _context.urunler.Add(urun);
                await _context.SaveChangesAsync();

                return RedirectToAction("AdminIndex","Admin");
            }
            else
            {
                ViewBag.Tablolar = new SelectList(_context.tablolar.ToList(),"tabloId","tabloName");
            ViewBag.Kategoriler = new SelectList(_context.kategoriler.ToList(),"kategoriId","kategoriName"); 
                return View();
            }
            
        }
        else
        {
            return RedirectToAction("Index","Admin");
        }
    }
    catch(Exception ex)
    {
        // Hata durumunda yapılacak işlemleri burada ele alabilirsiniz
        // Örneğin, hata mesajını loglamak, kullanıcıya hata mesajını göstermek gibi
        // Örnek olarak hata mesajını konsola yazdıralım:
        Console.WriteLine("Hata Oluştu: " + ex.Message);

        // İstisna durumu ele alındıktan sonra uygun bir şekilde kullanıcıya yönlendirme yapabilirsiniz.
        // Örneğin, bir hata sayfasına yönlendirme yapabilirsiniz.
        return RedirectToAction("Hata", "Home");
    }
}



}

Controllers/DeleteController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using admin_panel.Models;
using admin_panel.Data;
using admin_panel.Entity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin_panel.Controllers;

public class DeleteController : Controller
{
    private readonly MyContext _context;

    public DeleteController(MyContext context)
    {
        _context = context;
    }


    [HttpGet]
    public async Task<IActionResult> Index(int id)
    {   
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
                var product =await _context.urunler
                            .Include(x => x.Tablo)
                            .Include(x => x.Kategori)
                            .FirstOrDefaultAsync(x => x.Id == id);

                ViewBag.Tablolar = new SelectList(_context.tablolar.ToList(),"tabloId","tabloName");
                ViewBag.Kategoriler = new SelectList(_context.kategoriler.ToList(),"kategoriId","kategoriName"); 
                if (product == null)
                {
                    return NotFound(); // Ürün bulunamazsa hata sayfasına yönlendirme yapabilirsiniz
                }
            
            return View(product);
        }else{
            return RedirectToAction("Index","Admin");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {

        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
            var product = await _context.urunler.FindAsync(id);
            
            if(product == null)
            {
                return NotFound();
            }
                try
                {                   
                    _context.Remove(product);
                    await _context.SaveChangesAsync();   
                }
                catch (System.Exception)
                {              
                    throw;
                }
            
            
            return RedirectToAction("AdminIndex","Admin");

        }else{
            return RedirectToAction("Index","Admin");
        }
           
    }

}

Controllers/UpdateController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using admin_panel.Models;
using admin_panel.Data;
using admin_panel.Entity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin_panel.Controllers;

public class UpdateController : Controller
{
    private readonly MyContext _context;

    public UpdateController(MyContext context)
    {
        _context = context;
    }


    [HttpGet]
    public async Task<IActionResult> Index(int id)
    {   
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
                    var product =await _context.urunler
                            .Include(x => x.Tablo)
                            .Include(x => x.Kategori)
                            .FirstOrDefaultAsync(x => x.Id == id);

                            

                ViewBag.Tablolar = new SelectList(_context.tablolar.ToList(),"tabloId","tabloName");
                ViewBag.Kategoriler = new SelectList(_context.kategoriler.ToList(),"kategoriId","kategoriName"); 
                if (product == null)
                {
                    return NotFound(); // Ürün bulunamazsa hata sayfasına yönlendirme yapabilirsiniz
                }
                if(product.kategoriId == 5)
                {
                    return RedirectToAction("kampanyaEdit", new { id = product.Id });
                }
            
            return View(product);
        }else
        {
            return RedirectToAction("Index","Admin");
        }
        
    }

    [HttpGet]
    public async Task<IActionResult> kampanyaEdit(int id)
    {   
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
                    var product =await _context.urunler
                            .Include(x => x.Tablo)
                            .Include(x => x.Kategori)
                            .FirstOrDefaultAsync(x => x.Id == id);

                            
                if (product == null)
                {
                    return NotFound(); // Ürün bulunamazsa hata sayfasına yönlendirme yapabilirsiniz
                }
                
            
            return View(product);
        }else
        {
            return RedirectToAction("Index","Admin");
        }
        
    }

    [HttpPost]
    public async Task<IActionResult> Index(Urun model, int id)
    {
        if(HttpContext.Session.GetString("IsUserLoggedIn") == "true")
        {
            if(id != model.Id)
            {
               return NotFound();
            }
                try
                {                   
                    _context.Update(model);
                    await _context.SaveChangesAsync();   
                }
                catch (System.Exception)
                {              
                    throw;
                }
            
            
            return RedirectToAction("AdminIndex","Admin");
        }else
        {
            return RedirectToAction("Index","Admin");
        }
    }

}

Views/Admin/AdminIndex.cshtml
@using admin_panel.Models
@model admin_panel.Models.CountViewModel
@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Admin Page";
}
@section Styles { 
    <link href="~/css/myCss.css" rel="stylesheet">
}

<h1 style="text-align: center;">Sherlock House / Admin Panel</h1>

<div class="imagem" style="background-color: black;">
    <img src="~/logo.webp" alt="">
</div>
<hr>
<div class="row">
    <div class="col-md-10 mt-3">
        <p>
            Ürün Bilgi / <a asp-controller="Admin" asp-action="Menu" asp-route-category="hepsi" class="btn btn-info btn-sm">Tüm Ürünleri Göster</a>
        </p>
    </div>
    <div class="col-md-2 mt-3">
        <a asp-controller="Create" asp-action="Index" class="btn btn-primary">Yeni Ürün Ekle</a>
        <a asp-controller="Create" asp-action="Kampanya" asp-route-category="kampanya" class="btn btn-primary">Kampanya Ekle</a>
    </div>
    <div class="mt-3"><p> (Ürünler <b>güncellemek</b> veya <b>silmek</b> isterseniz, yan taraftaki kategoriler ile ürün seçimi yapınız.)</p></div>
    
</div>
<div class="row mt-3">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Yemekler (Adet)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            @if (Model != null && Model.IcecekCount != null)
                            {
                              @Model.YemekCount
                            }
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            İÇECEKLER (ADET)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                        
                            @if (Model != null && Model.IcecekCount != null)
                            {
                              @Model.IcecekCount
                            }
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            ALKOLLER (ADET)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            @if (Model != null && Model.IcecekCount != null)
                            {
                              @Model.AlkolCount
                            }
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            EXTRALAR (ADET)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            @if (Model != null && Model.IcecekCount != null)
                            {
                              @Model.ExtraCount
                            }
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            KAMPANYALAR (ADET)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            @if (Model != null && Model.IcecekCount != null)
                            {
                              @Model.KampanyaCount
                            }
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

 </div>
    <!--END-->

Views/Admin/Index.cshtml
@model LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SherlockHouse - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block">
                                <img src="~/images/logom.png" alt="" style="background-position:center; background-size: cover; width: 100%; height: 100%;" >
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Hoşgeldiniz!</h1>
                                    </div>
                                    <form asp-action="Index" method="post"  class="user">
                                        <div asp-validation-summary="All"></div>
                                        <div class="form-group">
                                            <input asp-for="userName"  class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input asp-for="password" type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                        <hr>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Admin/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SherlockHouse - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Hoşgeldiniz!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <a href="index.html" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a>
                                        <hr>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Admin/menu.cshtml
@using admin_panel.Entity
@using admin_panel.Data
@using admin_panel.Models
@model IEnumerable<Urun>
@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Ürünler";
}

<h1 style="text-align: center;">@ViewBag.category</h1>
<hr>
<a asp-controller="Create" asp-action="Index" class="btn btn-primary ml-3">Yeni Ekle</a>
<div class="row">
@foreach(var item in Model)
{
    
        <div class="card col-md-4 mt-3">
            <div>
                <img src="#" alt="" class="card-image">
            </div>
            <div class="card-body">
                <div class="card-title" style="font-weight:900;">@item.Name</div> <!-- Düzeltildi -->
                <div class="card-text">
                    <p>@item.Description</p>
                    
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-info">@item.Amount TL</button>
                <a class="btn btn-primary" asp-action="Index" asp-controller="Update" asp-route-id="@item.Id" style="width: 90px;">Güncelle</a>
                <a class="btn btn-danger" asp-action="Index" asp-controller="Delete" asp-route-id="@item.Id" style="width: 70px;">Sil</a>
            </div>
        </div>
    
}
</div>